[build]
  command = "pnpm run build"
  publish = "dist"

# ✅ SPA routing fix cho React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# ✅ Cache tối ưu cho assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
